#!/usr/bin/python3


def raise_exception_msg(message=""):
    """Raise a NameError exception and print the included message"""

    raise NameError(message)
